name: Flakie - Flaky test checker

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_target:
    types: [labeled]

jobs:
  flakie:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Build flakie CLI
        run: go build -o flakie ./cmd/flakie

      - name: Run tests multiple times
        id: run
        run: |
          set -e
          ./flakie -runs 5 -pkg ./... -timeout 10m -json > flakie.json || true
          echo "json<<EOF" >> $GITHUB_OUTPUT
          cat flakie.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: flakie-report
          path: flakie.json

      - name: Prepare comment
        id: prep
        run: |
          {
            echo "summary<<EOF"
            if command -v jq >/dev/null 2>&1; then
              RUNS=$(jq -r '.total_runs' flakie.json)
              echo "Flakie report (runs: ${RUNS})"
              echo
              FLAKY=$(jq -r '.flaky_tests[]?' flakie.json)
              if [ -n "$FLAKY" ]; then
                echo "Flaky tests detected:"
                echo "$FLAKY" | sed 's/^/- /'
              else
                echo "No flaky tests detected."
              fi
              FAILED=$(jq -r '.failed_tests[]?' flakie.json)
              if [ -n "$FAILED" ]; then
                echo
                echo "Consistently failing tests:"
                echo "$FAILED" | sed 's/^/- /'
              fi
            else
              echo "Flakie report could not parse JSON (jq missing). See flakie.json artifact."
            fi
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: flakie
          message: |
            🧪 Flakie report
            
            ${{ steps.prep.outputs.summary }}
